on: push

env:
  ARTIFACT_NAME: artifact123
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/upload-artifact@v1
      with:
    # Name of the artifact to upload.
    # Optional. Default is 'artifact'
        name: ${{ env.ARTIFACT_NAME }}
